env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  no-unused-vars: off
  import/extensions: off
  import/no-unresolved: off
  import/prefer-default-export: off

  arrow-body-style: off

  "react/jsx-filename-extension": off
  "react/jsx-props-no-spreading": off
  "jsx-a11y/click-events-have-key-events": off
  "jsx-a11y/no-static-element-interactions": off
  "jsx-a11y/anchor-is-valid": off
  "react/function-component-definition":
    - error
    - "namedComponents": arrow-function
      "unnamedComponents": arrow-function

  "@typescript-eslint/no-unused-vars": off
