inherit_from:
  - config/rubocop/rules_due_to_warning.yml

AllCops:
  Exclude:
    - "bin/**/*"
    - "spec/spec_helper.rb"
    - "db/schema.rb"
    - "db/migrate/*"
    - "app/graphql/backend_schema.rb"
    - "app/controllers/graphql_controller.rb"

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/HashSyntax:
  Enabled: true
Style/AccessorGrouping:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  Enabled: false # 後で一括適用
  #  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  Enabled: false # 後で一括適用
  #  EnforcedStyleForMultiline: comma
Style/NumericPredicate:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent